# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- task*

pool:
  vmImage: 'Ubuntu-18.04'

jobs:
  - job: Build
    displayName: Build Maven Project
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'application/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'verify'
        options: '-DskipTests'
    - task: Maven@1
      inputs:
        mavenPomFile: 'service/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenOptions: '-Xmx3072m'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        mavenVersionOption: 'Default'
        goals: 'verify'
        options: '-DskipTests'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

  - deployment: VMDeploy
    displayName: web
    pool:
      vmImage: 'Ubuntu-18.04'
    environment:
      name: VM
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment